version: "3"
services:
  # Server
  WebServer:
    container_name: ServerPhp8.4
    image: nginx:latest
    restart: always
    ports:
        - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    networks:
      - my-network
   #PHP
  php:
    container_name: php84
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=localhost"
    networks:
      - my-network
  # MySQL
  mysql:
    container_name: mySqlPhp8.4
    image: mysql:8.0
    networks:
      - my-network
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_vasya
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: { }

# Define networks
networks:
  my-network:
    driver: bridge
